# src/auth/interfaces.py
from typing import Optional, Dict, Any, Protocol

class AuthService(Protocol):
    def login(self, username: str, password: str) -> bool: ...
    def logout(self) -> None: ...
    def current_user(self) -> Optional[Dict[str, Any]]: ...
    def has_role(self, role: str) -> bool: ...
    def refresh_token(self) -> bool: ...
