name: Build Windows EXE
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller
      - name: Build (PyInstaller)
        shell: bash
        run: |
          if [ -f "AlbionBeacon.spec" ]; then
            pyinstaller --noconfirm AlbionBeacon.spec
          else
            pyinstaller --noconfirm --onefile --name AlbionBeacon src\\client\\main.py
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AlbionBeacon-exe
          path: dist/AlbionBeacon.exe
