name: Blueprint Watch

on:
  push:
    paths:
      - "docs/PROJECT_GUIDELINES.md"
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  notify:
    runs-on: windows-latest
    steps:
      - name: Open issue about blueprint change
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.sha;
            const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${tag}`;
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "GuideLines updated",
              body: [
                "docs/blueprint.md has been updated.",
                "",
                `Commit: ${tag}`,
                `Author: ${context.actor}`,
                `Compare: ${url}`
              ].join("\n"),
              labels: ["blueprint","notice"]
            });
