name: Guidelines Watch

on:
  push:
    paths:
      - "docs/PROJECT_GUIDELINES.md"
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue notifying guideline changes
        uses: actions/github-script@v7
        with:
          script: |
            const now = new Date().toISOString();
            const title = `Guidelines updated @ ${now}`;
            const body = `
**docs/PROJECT_GUIDELINES.md** has been updated.

- Commit: ${context.sha}
- Author: ${context.actor}
- Compare: https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}

Please review the latest rules and ensure Gemini/GPT both use this version.
`;
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ["guidelines", "notice"]
            });
