name: Blueprint Watch

on:
  push:
    paths:
      - "docs/blueprint.md"
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue notifying blueprint changes
        uses: actions/github-script@v7
        with:
          script: |
            const now = new Date().toISOString();
            const title = `Blueprint updated @ ${now}`;
            const body = `
**docs/blueprint.md** has been updated.

- Commit: ${context.sha}
- Author: ${context.actor}
- Compare: https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}

Ensure the latest blueprint is used for all upcoming tasks.
`;
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ["blueprint", "notice"]
            });
